name: LangSign_Detection
channels:
  - defaults
dependencies:
  - altair=6.0.0=py312haa95532_1
  - annotated-doc=0.0.4=py312haa95532_0
  - annotated-types=0.6.0=py312haa95532_1
  - anyio=4.10.0=py312haa95532_0
  - arrow-cpp=21.0.0=h6358905_1
  - attrs=25.4.0=py312haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - blinker=1.9.0=py312haa95532_1
  - bottleneck=1.4.2=py312h540bb41_1
  - brotlicffi=1.2.0.0=py312h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=h2c209ce_0
  - ca-certificates=2025.12.2=haa95532_0
  - cachetools=6.2.2=py312haa95532_0
  - certifi=2026.01.04=py312haa95532_0
  - cffi=2.0.0=py312h02ab6af_1
  - charset-normalizer=3.4.4=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - dnspython=2.8.0=py312haa95532_0
  - email-validator=2.3.0=py312haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - fastapi=0.128.0=py312haa95532_0
  - fastapi-cli=0.0.20=py312haa95532_0
  - fastapi-core=0.128.0=py312haa95532_0
  - freetype=2.14.1=hfbffc0b_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py312haa95532_0
  - gitpython=3.1.46=py312haa95532_0
  - glog=0.5.0=hd77b12b_1
  - h11=0.16.0=py312haa95532_1
  - httpcore=1.0.9=py312haa95532_0
  - httptools=0.7.1=py312h02ab6af_0
  - httpx=0.28.1=py312haa95532_1
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.11=py312haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.3=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.1=py312haa95532_0
  - jsonschema-specifications=2025.9.1=py312haa95532_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.17.0=h6e672f4_1
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc89ec93_0
  - libkrb5=1.22.1=hb237eb7_0
  - libpng=1.6.54=ha15c746_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py312haa95532_1
  - mdurl=0.1.2=py312haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - narwhals=2.7.0=py312haa95532_0
  - nltk=3.9.2=py312ha55a155_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy-base=2.4.2=py312h1df51cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.19=hbb43b14_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312h42c1672_1
  - pip=26.0.1=pyhc872135_0
  - pyarrow=21.0.0=py312h42c1672_1
  - pydantic=2.12.4=py312haa95532_0
  - pydantic-core=2.41.5=py312h114bc41_1
  - pydantic-extra-types=2.11.0=py312haa95532_0
  - pydantic-settings=2.12.0=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - pysocks=1.7.1=py312haa95532_1
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-dotenv=1.2.1=py312haa95532_0
  - python-multipart=0.0.22=py312haa95532_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py312haa95532_0
  - pyyaml=6.0.3=py312hb9a58be_0
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py312haa95532_0
  - regex=2025.11.3=py312h02ab6af_0
  - requests=2.32.5=py312haa95532_1
  - rich-toolkit=0.17.1=py312haa95532_0
  - rpds-py=0.28.0=py312h114bc41_0
  - scikit-learn=1.7.1=py312h3fbe716_0
  - scipy=1.17.0=py312h2074b4c_0
  - setuptools=80.10.2=py312haa95532_0
  - shellingham=1.5.4=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - smmap=5.0.2=py312haa95532_0
  - snappy=1.2.2=hab6b7b3_1
  - sniffio=1.3.1=py312haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - starlette=0.47.3=py312haa95532_0
  - streamlit=1.54.0=py312haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tenacity=9.1.2=py312haa95532_1
  - threadpoolctl=3.5.0=py312h4442805_1
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.4=py312h02ab6af_0
  - tqdm=4.67.3=py312h4442805_1
  - typer=0.20.0=py312haa95532_1
  - typer-slim=0.20.0=py312haa95532_1
  - typer-slim-standard=0.20.0=py312haa95532_1
  - typing-extensions=4.15.0=py312haa95532_0
  - typing-inspection=0.4.2=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py312haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - uvicorn=0.40.0=py312haa95532_0
  - uvicorn-standard=0.40.0=py312haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py312haa95532_0
  - watchfiles=1.1.1=py312h114bc41_1
  - websockets=15.0.1=py312h827c3e9_0
  - wheel=0.46.3=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.4.0
      - aioice==0.10.2
      - aiortc==1.14.0
      - astunparse==1.6.3
      - av==16.1.0
      - beautifulsoup4==4.14.3
      - click==8.1.8
      - comtypes==1.4.15
      - contourpy==1.3.3
      - cryptography==46.0.5
      - cvzone==1.6.1
      - cycler==0.12.1
      - deep-translator==1.11.4
      - editdistpy==0.2.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - gast==0.7.0
      - google-crc32c==1.8.0
      - google-pasta==0.2.0
      - grpcio==1.78.0
      - gtts==2.5.4
      - h5py==3.15.1
      - ifaddr==0.2.0
      - jax==0.9.0.1
      - jaxlib==0.9.0.1
      - keras==3.10.0
      - kiwisolver==1.4.9
      - language-tool-python==3.2.2
      - libclang==18.1.1
      - markdown==3.10.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mediapipe==0.10.14
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - numpy==2.0.2
      - opencv-contrib-python==4.13.0.92
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pillow==12.1.1
      - protobuf==4.25.8
      - psutil==7.2.2
      - pycparser==3.0
      - pyee==13.0.1
      - pygame==2.6.1
      - pylibsrtp==1.0.0
      - pyopenssl==25.3.0
      - pyparsing==3.3.2
      - pypiwin32==223
      - pyspellchecker==0.8.4
      - pyttsx3==2.99
      - pywin32==311
      - rich==14.3.2
      - sounddevice==0.5.5
      - soupsieve==2.8.3
      - streamlit-webrtc==0.64.5
      - symspellpy==6.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==3.3.0
      - werkzeug==3.1.6
      - wrapt==2.1.1
prefix: C:\Users\akshb\anaconda3\envs\LangSign_Detection
